//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Generated by Swift-Viper templates. Find latest version at https://github.com/Nikita2k/SwiftViper
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___Controller: UIViewController {
	
	var presenter: ___FILEBASENAMEASIDENTIFIER___PresenterProtocol!

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
}

extension ___FILEBASENAMEASIDENTIFIER___Controller: ___FILEBASENAMEASIDENTIFIER___InterfaceProtocol {
    
}